name: Check markdown links

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Every month

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sosiristseng/docker-juliabook:1.7.3.4
    steps:
      - uses: actions/checkout@v3
      - run: jupyter-book build docs/ --builder linkcheck

      # - name: Build Jupyter Books
      #   run: docker run -v ${{ github.workspace }}:/work ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest jupyter-book build /work/docs --builder linkcheck
